---
- name: Terminate instances
  hosts: myserver
  connection: local
  tasks:
    - name: Terminate instances
      ec2:
        state: 'absent'
        instance_ids: 'i-07daea57c0e8660f5'
        region: 'us-west-2'
