---
- hosts: myserver
  sudo: yes
  remote_user: ubuntu
  tasks:
   - name: Install apache
     apt: name=apache2 update_cache=yes state=latest

   - name: apache2 module rewrite
     apache2_module: name=rewrite state=present
     notify:
      - restart apache2

   - name: copy the file
     copy: src=hellosource.html dest=/var/www/hellohost.html

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
